export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FAILED = 'AUTH_FAILED';
export const RESET_HASH_SENT = 'RESET_HASH_SENT';
export const RESET_HASH_IS_VALID = 'RESET_HASH_IS_VALID';
export const RESET_HASH_IS_NOT_VALID = 'RESET_HASH_IS_NOT_VALID';
export const RESET_AUTH_NOTIFICATIONS = 'RESET_AUTH_NOTIFICATIONS';
